(()=>{"use strict";
const cfg=window.BLACK_HEART_CONFIG||{};
async function resolveLiffId(){
  const urlId=new URLSearchParams(location.search).get('liffId')||'';
  if(urlId){try{localStorage.setItem('blackheart_liff_id',urlId)}catch{};cfg.LIFF_ID=urlId;return urlId}
  const direct=String(cfg.LIFF_ID||'').trim();if(direct)return direct;
  try{const saved=String(localStorage.getItem('blackheart_liff_id')||'').trim();if(saved){cfg.LIFF_ID=saved;return saved}}catch{}
  const endpoint=String(cfg.PUBLIC_CONFIG_URL||'').trim();if(!endpoint)return '';
  try{const sep=endpoint.includes('?')?'&':'?';const r=await fetch(endpoint+sep+'_='+Date.now(),{cache:'no-store'});const d=await r.json();const id=String(d&&d.liffId||'').trim();if(id){cfg.LIFF_ID=id;try{localStorage.setItem('blackheart_liff_id',id)}catch{};return id}}catch(e){console.warn('LIFF 公開設定讀取失敗',e)}
  return ''
}
const $=id=>document.getElementById(id);
const el={testControls:$("testControls"),testBalls:$("testBalls"),testDrinks:$("testDrinks"),testMeals:$("testMeals"),storeStatus:$("storeStatus"),statusDot:$("statusDot"),waitMinutes:$("waitMinutes"),storeNotice:$("storeNotice"),loginPanel:$("loginPanel"),memberPanel:$("memberPanel"),memberName:$("memberName"),memberPicture:$("memberPicture"),lineLoginBtn:$("lineLoginBtn"),previewBtn:$("previewBtn"),startOrderBtn:$("startOrderBtn"),loginHint:$("loginHint"),menuSection:$("menuSection"),categoryTabs:$("categoryTabs"),productList:$("productList"),catalogMeta:$("catalogMeta"),productModal:$("productModal"),modalContent:$("modalContent"),cartBar:$("cartBar"),cartCount:$("cartCount"),cartTotal:$("cartTotal"),cartModal:$("cartModal"),cartItems:$("cartItems"),cartModalTotal:$("cartModalTotal"),clearCartBtn:$("clearCartBtn"),checkoutBtn:$("checkoutBtn"),checkoutModal:$("checkoutModal"),checkoutForm:$("checkoutForm"),customerName:$("customerName"),customerPhone:$("customerPhone"),pickupTime:$("pickupTime"),orderNote:$("orderNote"),checkoutTotal:$("checkoutTotal"),orderResultModal:$("orderResultModal"),orderResultText:$("orderResultText"),copyOrderBtn:$("copyOrderBtn"),continueOrderBtn:$("continueOrderBtn"),myOrdersBtn:$("myOrdersBtn"),myOrdersBadge:$("myOrdersBadge"),currentOrderPanel:$("currentOrderPanel"),myOrdersModal:$("myOrdersModal"),myOrdersList:$("myOrdersList"),orderDetailModal:$("orderDetailModal"),orderDetailContent:$("orderDetailContent"),toast:$("toast")};
const state={catalog:null,categories:[],displayProducts:[],activeCategory:"balls",drinkSubcategory:"",cart:loadCart(),profile:null,preview:false,current:null,editingId:null,lastOrderText:"",accepting:{balls:true,drinks:true,meals:false},waitTime:10,notice:"",posStatusConnected:false,posStatusUpdatedAt:"",posStatusErrorShown:false,posStatusFailCount:0,posStatusPollTimer:null,myOrders:[],myOrdersBusy:false,myOrdersTimer:null};
const LOCAL_ORDERS_KEY="blackheart_recent_orders_v3";
function loadLocalOrders(){try{const a=JSON.parse(localStorage.getItem(LOCAL_ORDERS_KEY)||"[]");return Array.isArray(a)?a:[]}catch{return []}}
function saveLocalOrders(list){try{localStorage.setItem(LOCAL_ORDERS_KEY,JSON.stringify((Array.isArray(list)?list:[]).slice(0,20)))}catch{}}
function rememberLocalOrder(order){const list=loadLocalOrders().filter(x=>String(x.orderId)!==String(order.orderId));list.unshift(order);saveLocalOrders(list)}
function mergeOrders(cloud,local){const map=new Map();[...(Array.isArray(local)?local:[]),...(Array.isArray(cloud)?cloud:[])].forEach(o=>{if(o&&o.orderId)map.set(String(o.orderId),{...(map.get(String(o.orderId))||{}),...o})});return [...map.values()].filter(o=>{const d=new Date(o.createdAt||0);return orderActive(o.status)||(!isNaN(d)&&Date.now()-d.getTime()<=3*86400000)}).sort((a,b)=>(orderActive(b.status)-orderActive(a.status))||(new Date(b.createdAt)-new Date(a.createdAt)))}
const money=n=>`NT$${Number(n||0).toLocaleString("zh-TW")}`;
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function toast(m){el.toast.textContent=m;el.toast.classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.add("hidden"),2400)}
function loadCart(){try{return JSON.parse(localStorage.getItem("blackheartorder_cart")||"[]")}catch{return[]}}
function saveCart(){localStorage.setItem("blackheartorder_cart",JSON.stringify(state.cart))}
function setStore(){const s=cfg.STORE||{},anyOpen=state.accepting.balls||state.accepting.drinks||state.accepting.meals;el.storeStatus.textContent=anyOpen?(s.statusText||"今日營業中"):"今日暫停接單";el.waitMinutes.textContent=anyOpen?(state.waitTime>0?`約 ${state.waitTime} 分鐘`:"可立即取餐"):"暫停接單";el.storeNotice.textContent=state.notice||s.notice||"";el.statusDot.classList.toggle("closed",!anyOpen)}
function isHidden(p){const words=cfg.HIDDEN_PRODUCT_KEYWORDS||[];return p.enabled===false||words.some(w=>String(p.name||"").includes(w))}
function categoryKey(p){const t=p?.product_type||p?.type;return t==="ball"||t==="ball_bundle"?"balls":t==="meal"?"meals":"drinks"}
function categoryName(key){return key==="balls"?"🍠 地瓜球":key==="drinks"?"🥤 飲料":"🍱 餐點"}
function categoryOpen(key){return cfg.STORE?.isOpen!==false&&state.accepting[key]!==false}
function categoryClosedText(key){return state.accepting[key]===false?"目前停止接單":"今日暫停接單"}
function syncAccepting(){const base=cfg.ORDER_STATUS||{};state.accepting={balls:base.balls!==false,drinks:base.drinks!==false,meals:base.meals===true};if(!String(cfg.POS_STATUS_URL||"").trim()&&cfg.ENABLE_TEST_SWITCHES!==false){try{const saved=JSON.parse(localStorage.getItem("blackheartorder_test_status")||"null");if(saved)state.accepting={...state.accepting,...saved}}catch{}}}
function saveAccepting(){localStorage.setItem("blackheartorder_test_status",JSON.stringify(state.accepting))}
function renderTestControls(){if(!el.testControls)return;const apiEnabled=Boolean(String(cfg.POS_STATUS_URL||"").trim());el.testControls.classList.toggle("hidden",apiEnabled||cfg.ENABLE_TEST_SWITCHES===false);for(const [key,node] of [["balls",el.testBalls],["drinks",el.testDrinks],["meals",el.testMeals]])if(node){node.checked=state.accepting[key]!==false;node.closest("label")?.classList.toggle("off",!node.checked)}}
function boolValue(v,fallback){if(typeof v==="boolean")return v;if(typeof v==="number")return v!==0;if(typeof v==="string"){const x=v.trim().toLowerCase();if(["true","1","open","opened","on","yes","營業","開賣","接單"].includes(x))return true;if(["false","0","closed","close","off","no","停售","停止","售完"].includes(x))return false}return fallback}
function parsePosStatus(data){const root=data?.orderStatus||data?.order_status||data?.status||data||{};return {balls:boolValue(root.balls??root.sweetpotato??root.sweetPotato??root.ball,state.accepting.balls),drinks:boolValue(root.drinks??root.drink,state.accepting.drinks),meals:boolValue(root.meals??root.meal??root.food,state.accepting.meals),waitTime:Math.max(0,Math.min(180,Number(root.waitTime??root.wait_time??data?.waitTime??state.waitTime)||0)),notice:String(root.notice??data?.notice??state.notice??""),updatedAt:data?.updatedAt||data?.updated_at||root.updatedAt||root.updated_at||""}}
async function refreshPosStatus(silent=true){const url=String(cfg.POS_STATUS_URL||"").trim();if(!url)return true;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const sep=url.includes("?")?"&":"?";const r=await fetch(`${url}${sep}_=${Date.now()}`,{cache:"no-store",signal:controller.signal,headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();if(data?.ok===false)throw new Error(data.message||"POS 狀態 API 回傳失敗");const next=parsePosStatus(data);const changed=["balls","drinks","meals"].some(k=>state.accepting[k]!==next[k]);state.accepting={balls:next.balls,drinks:next.drinks,meals:next.meals};state.waitTime=next.waitTime;state.notice=next.notice;setStore();state.posStatusConnected=true;state.posStatusUpdatedAt=next.updatedAt||new Date().toISOString();state.posStatusErrorShown=false;state.posStatusFailCount=0;if(changed){renderProducts();renderCart()}renderTestControls();return true}catch(e){console.warn("POS status sync failed; keeping last known status",e);state.posStatusConnected=false;state.posStatusFailCount=(state.posStatusFailCount||0)+1;return false}finally{clearTimeout(timer)}}
function startPosStatusPolling(){const url=String(cfg.POS_STATUS_URL||"").trim();if(!url)return;const normalMs=Math.max(5000,Number(cfg.POS_STATUS_POLL_MS||10000));const schedule=async(immediate=false)=>{if(state.posStatusPollTimer)clearTimeout(state.posStatusPollTimer);if(!immediate&&document.visibilityState==="hidden"){state.posStatusPollTimer=setTimeout(()=>schedule(false),30000);return}const ok=await refreshPosStatus(true);const retryMs=ok?normalMs:Math.min(60000,normalMs*Math.max(2,state.posStatusFailCount||1));state.posStatusPollTimer=setTimeout(()=>schedule(false),retryMs)};schedule(true);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")schedule(true)})}
function validateCartAvailability(){const blocked=[...new Set(state.cart.filter(x=>!categoryOpen(x.categoryKey||categoryKey(x))).map(x=>x.categoryKey||categoryKey(x)))];return blocked}
function buildCatalog(raw){
 const products=(raw.products||[]).filter(p=>!isHidden(p));
 const balls=products.filter(p=>p.product_type==="ball").sort(sortByOrder);
 const others=products.filter(p=>p.product_type!=="ball");
 const ballCard=balls.length?{product_id:"online_ball_bundle",category_id:"balls",category_name:"地瓜球",name:cfg.BALL_PRODUCT_NAME||"黑心地瓜球",product_type:"ball_bundle",base_price:Math.min(...balls.map(x=>Number(x.base_price||0))),flavors:balls,enabled:true,sort_order:0}:null;
 state.displayProducts=[...(ballCard?[ballCard]:[]),...others];
 state.drinkCategories=(raw.categories||[]).filter(c=>c.enabled!==false&&c.category_id.startsWith("drink_")&&others.some(p=>p.category_id===c.category_id)).sort(sortByOrder);
 const categories=[];
 if(ballCard)categories.push({category_id:"balls",name:"🍠 地瓜球",enabled:true,sort_order:10});
 if(others.some(p=>categoryKey(p)==="drinks"))categories.push({category_id:"drinks",name:"🥤 飲料",enabled:true,sort_order:20});
 if(others.some(p=>categoryKey(p)==="meals"))categories.push({category_id:"meals",name:"🍱 餐點",enabled:true,sort_order:30});
 state.categories=categories;
 if(!state.categories.some(c=>c.category_id===state.activeCategory))state.activeCategory=state.categories[0]?.category_id||"";
 el.catalogMeta.textContent=`${state.displayProducts.length} 項商品`;
 renderTabs();renderProducts();renderCart();renderTestControls()
}
function sortByOrder(a,b){return Number(a.sort_order||0)-Number(b.sort_order||0)}
function renderTabs(){
 el.categoryTabs.innerHTML=state.categories.map(c=>`<button class="category-tab ${c.category_id===state.activeCategory?"active":""}" data-cat="${esc(c.category_id)}">${esc(c.name)}</button>`).join("");
 el.categoryTabs.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{state.activeCategory=b.dataset.cat;state.drinkSubcategory="";renderTabs();renderProducts()})
}
function priceText(p){if(p.product_type==="ball_bundle")return `${money(p.base_price)} 起`;const vars=(p.variants||[]).filter(v=>v.enabled);if(vars.length){const xs=vars.map(v=>Number(v.price));return Math.min(...xs)===Math.max(...xs)?money(xs[0]):`${money(Math.min(...xs))} 起`}return money(p.base_price)}
function iconFor(p){return p.product_type==="drink"?"🥤":p.product_type==="meal"?"🍱":"🍠"}
function productHint(p){const bits=[];if((p.variants||[]).filter(v=>v.enabled).length)bits.push("可選尺寸");for(const g of p.option_groups||[])if(g.name&&!bits.includes(g.name))bits.push(g.name);return bits.length?bits.join("・"):"點選查看"}
function renderProducts(){
 if(state.activeCategory==="drinks"&&!state.drinkSubcategory){
  const open=categoryOpen("drinks");
  el.productList.innerHTML=`<div class="subcategory-heading"><div><p class="section-label">DRINKS</p><h3>選擇飲料分類</h3></div></div><div class="subcategory-grid">${state.drinkCategories.map(c=>{const count=state.displayProducts.filter(p=>p.category_id===c.category_id).length;return `<button class="subcategory-card ${open?"":"unavailable"}" data-drink-cat="${esc(c.category_id)}"><span>${esc(c.name)}</span><small>${count} 項商品</small><b>›</b></button>`}).join("")}</div>${open?"":`<div class="category-closed-banner">飲料目前停止接單，仍可查看品項。</div>`}`;
  el.productList.querySelectorAll("[data-drink-cat]").forEach(b=>b.onclick=()=>{state.drinkSubcategory=b.dataset.drinkCat;renderProducts()});return
 }
 let list=[];
 if(state.activeCategory==="balls")list=state.displayProducts.filter(p=>p.category_id==="balls");
 else if(state.activeCategory==="meals")list=state.displayProducts.filter(p=>categoryKey(p)==="meals");
 else if(state.activeCategory==="drinks")list=state.displayProducts.filter(p=>p.category_id===state.drinkSubcategory);
 list.sort(sortByOrder);
 const back=state.activeCategory==="drinks"?`<button class="back-category-btn" id="backToDrinkCategories">← 返回飲料分類</button>`:"";
 el.productList.innerHTML=back+(list.length?list.map(p=>{const key=categoryKey(p),open=categoryOpen(key);return `<button class="product-card ${open?"":"unavailable"}" data-product="${esc(p.product_id)}" ${open?"":"aria-disabled=\"true\""}><div class="product-placeholder">${iconFor(p)}</div><div class="product-info"><h3>${esc(p.name)}</h3><p>${open?(p.product_type==="ball_bundle"?"最多選 2 種口味・價格取最高價":esc(productHint(p))):categoryClosedText(key)}</p></div><strong class="product-price">${open?priceText(p):"停止接單"}</strong></button>`}).join(""):`<div class="empty-state">此分類目前沒有商品</div>`);
 $("backToDrinkCategories")?.addEventListener("click",()=>{state.drinkSubcategory="";renderProducts()});
 el.productList.querySelectorAll("[data-product]").forEach(b=>b.onclick=()=>{const p=state.displayProducts.find(p=>p.product_id===b.dataset.product);if(!categoryOpen(categoryKey(p)))return toast(`${categoryName(categoryKey(p)).replace(/^.. /,"")}目前停止接單`);openProduct(p)})
}
function openProduct(p,cartItem=null){if(!p)return;if(!categoryOpen(categoryKey(p)))return toast("此分類目前停止接單");state.editingId=cartItem?.id||null;state.current={p,qty:cartItem?.qty||1,flavors:[],ballOptions:{},variant:null,options:{}};if(cartItem){if(p.product_type==="ball_bundle"){state.current.flavors=p.flavors.filter(f=>(cartItem.flavorIds||[]).includes(f.product_id));state.current.ballOptions=cartItem.ballOptionIds||{}}else{state.current.variant=(p.variants||[]).find(v=>v.variant_id===cartItem.variantId)||null;for(const [gid,ids] of Object.entries(cartItem.optionIds||{})){const g=(p.option_groups||[]).find(x=>x.option_group_id===gid);state.current.options[gid]=(g?.items||[]).filter(x=>ids.includes(x.option_item_id))}}}p.product_type==="ball_bundle"?renderBallModal():renderRegularModal();showModal(el.productModal)}
function renderBallModal(){
 const c=state.current,p=c.p;const highest=c.flavors.length?Math.max(...c.flavors.map(x=>Number(x.base_price))):Number(p.base_price);
 const extra=c.flavors.map(f=>{const groups=f.option_groups||[];if(!groups.length)return "";return groups.map(g=>{const items=(g.items||[]).filter(x=>x.enabled!==false).sort(sortByOrder);const selected=c.ballOptions[f.product_id]?.[g.option_group_id]||[];return `<section class="choice-section flavor-extra"><h3>${esc(f.name)}｜${esc(g.name)}</h3><p class="choice-help">${g.required?"請選擇 1 項":"可不選"}</p><div class="choice-grid">${items.map(x=>`<button class="choice ${selected.includes(x.option_item_id)?"selected":""}" data-ball-flavor="${esc(f.product_id)}" data-ball-group="${esc(g.option_group_id)}" data-ball-option="${esc(x.option_item_id)}"><span>${esc(x.name)}</span><small>${Number(x.price_delta||0)?`+${money(x.price_delta)}`:""}</small></button>`).join("")}</div></section>`}).join("")}).join("");
 el.modalContent.innerHTML=`<div class="modal-title"><p class="section-label">地瓜球</p><h2 id="modalTitle">${esc(p.name)}</h2><p>一份最多選 2 種口味，價格以所選口味中的最高價計算。</p></div><section class="choice-section"><h3>選擇口味</h3><p class="choice-help">至少選 1 種，最多 2 種</p><div class="choice-grid">${p.flavors.map(f=>`<button class="choice ${c.flavors.some(x=>x.product_id===f.product_id)?"selected":""}" data-flavor="${esc(f.product_id)}"><span>${esc(f.name)}</span><small>${money(f.base_price)}</small></button>`).join("")}</div></section>${extra}${qtyHtml(c.qty)}<div class="add-row"><button id="addCurrentBtn" class="primary-btn" ${c.flavors.length?"":"disabled"}><span>${state.editingId?"儲存修改":"加入購物車"}</span><strong>${money(highest*c.qty)}</strong></button></div>`;
 el.modalContent.querySelectorAll("[data-flavor]").forEach(b=>b.onclick=()=>{const f=p.flavors.find(x=>x.product_id===b.dataset.flavor),i=c.flavors.findIndex(x=>x.product_id===f.product_id);if(i>=0){c.flavors.splice(i,1);delete c.ballOptions[f.product_id]}else if(c.flavors.length>=2)return toast("最多選擇 2 種口味");else c.flavors.push(f);renderBallModal()});
 el.modalContent.querySelectorAll("[data-ball-option]").forEach(b=>b.onclick=()=>toggleBallOption(b.dataset.ballFlavor,b.dataset.ballGroup,b.dataset.ballOption));
 bindQty();$("addCurrentBtn")?.addEventListener("click",addCurrent)
}
function toggleBallOption(fid,gid,oid){
 const c=state.current,f=c.p.flavors.find(x=>x.product_id===fid),g=(f.option_groups||[]).find(x=>x.option_group_id===gid);c.ballOptions[fid]||={};let arr=c.ballOptions[fid][gid]||[];const i=arr.indexOf(oid);
 if(Number(g.max_select||1)===1)arr=i>=0&&!g.required?[]:[oid];else if(i>=0)arr.splice(i,1);else if(arr.length<Number(g.max_select||99))arr.push(oid);else return toast(`最多選擇 ${g.max_select} 項`);
 c.ballOptions[fid][gid]=arr;renderBallModal()
}
function renderRegularModal(){const c=state.current,p=c.p;const vars=(p.variants||[]).filter(v=>v.enabled).sort(sortByOrder);if(vars.length&&!c.variant)c.variant=vars[0];for(const g of p.option_groups||[]){const items=(g.items||[]).filter(x=>x.enabled).sort(sortByOrder);if(g.required&&!c.options[g.option_group_id]&&items.length)c.options[g.option_group_id]=[items[0]]}const unit=calcRegularUnit(c);const groups=(p.option_groups||[]).sort(sortByOrder).map(g=>groupHtml(g,c.options[g.option_group_id]||[])).join("");el.modalContent.innerHTML=`<div class="modal-title"><p class="section-label">${esc(p.category_name||"商品")}</p><h2 id="modalTitle">${esc(p.name)}</h2><p>${esc(productHint(p))}</p></div>${vars.length?`<section class="choice-section"><h3>尺寸</h3><div class="choice-grid">${vars.map(v=>`<button class="choice ${c.variant?.variant_id===v.variant_id?"selected":""}" data-variant="${esc(v.variant_id)}"><span>${esc(v.name)}</span><small>${money(v.price)}</small></button>`).join("")}</div></section>`:""}${groups}${qtyHtml(c.qty)}<div class="add-row"><button id="addCurrentBtn" class="primary-btn"><span>${state.editingId?"儲存修改":"加入購物車"}</span><strong>${money(unit*c.qty)}</strong></button></div>`;el.modalContent.querySelectorAll("[data-variant]").forEach(b=>b.onclick=()=>{c.variant=vars.find(v=>v.variant_id===b.dataset.variant);renderRegularModal()});el.modalContent.querySelectorAll("[data-option]").forEach(b=>b.onclick=()=>toggleOption(b.dataset.group,b.dataset.option));bindQty();$("addCurrentBtn").onclick=addCurrent}
function groupHtml(g,selected){const items=(g.items||[]).filter(x=>x.enabled).sort(sortByOrder);return `<section class="choice-section"><h3>${esc(g.name)}${g.required?" *":""}</h3><p class="choice-help">${Number(g.max_select)===1?"請選擇 1 項":`最多選 ${g.max_select} 項`}</p><div class="choice-grid">${items.map(x=>`<button class="choice ${selected.some(s=>s.option_item_id===x.option_item_id)?"selected":""}" data-group="${esc(g.option_group_id)}" data-option="${esc(x.option_item_id)}"><span>${esc(x.name)}</span><small>${Number(x.price_delta)?`+${money(x.price_delta)}`:""}</small></button>`).join("")}</div></section>`}
function toggleOption(gid,oid){const c=state.current,g=(c.p.option_groups||[]).find(x=>x.option_group_id===gid),item=(g.items||[]).find(x=>x.option_item_id===oid),arr=c.options[gid]||[],i=arr.findIndex(x=>x.option_item_id===oid);if(Number(g.max_select)===1)c.options[gid]=i>=0&&!g.required?[]:[item];else if(i>=0)arr.splice(i,1);else if(arr.length<Number(g.max_select||99))arr.push(item);else return toast(`最多選擇 ${g.max_select} 項`);renderRegularModal()}
function calcRegularUnit(c){let unit=c.variant?Number(c.variant.price):Number(c.p.base_price);for(const xs of Object.values(c.options))unit+=xs.reduce((s,x)=>s+Number(x.price_delta||0),0);return unit}
function qtyHtml(q){return `<div class="qty-row"><strong>數量</strong><div class="qty-control"><button data-qty="-1">−</button><strong>${q}</strong><button data-qty="1">＋</button></div></div>`}
function bindQty(){el.modalContent.querySelectorAll("[data-qty]").forEach(b=>b.onclick=()=>{state.current.qty=Math.max(1,Math.min(99,state.current.qty+Number(b.dataset.qty)));state.current.p.product_type==="ball_bundle"?renderBallModal():renderRegularModal()})}
function addCurrent(){const c=state.current,p=c.p;if(!categoryOpen(categoryKey(p)))return toast("此分類已停止接單，無法加入購物車");let item;if(p.product_type==="ball_bundle"){if(!c.flavors.length)return toast("請先選擇口味");for(const f of c.flavors)for(const g of f.option_groups||[])if(g.required&&!(c.ballOptions[f.product_id]?.[g.option_group_id]||[]).length)return toast(`請選擇${f.name}的${g.name}`);const unit=Math.max(...c.flavors.map(x=>Number(x.base_price)));const flavorTexts=c.flavors.map(f=>{const opts=[];for(const g of f.option_groups||[]){const ids=c.ballOptions[f.product_id]?.[g.option_group_id]||[];const names=(g.items||[]).filter(x=>ids.includes(x.option_item_id)).map(x=>x.name);if(names.length)opts.push(names.join("、"))}return opts.length?`${f.name}（${opts.join("、")}）`:f.name});item={id:state.editingId||cryptoId(),productId:p.product_id,type:p.product_type,categoryKey:categoryKey(p),name:p.name,qty:c.qty,unit,detail:[`口味：${flavorTexts.join("＋")}`],flavorIds:c.flavors.map(x=>x.product_id),ballOptionIds:c.ballOptions}}else{for(const g of p.option_groups||[]){if(g.required&&!(c.options[g.option_group_id]||[]).length)return toast(`請選擇${g.name}`)}let detail=[];if(c.variant)detail.push(`尺寸：${c.variant.name}`);for(const g of p.option_groups||[]){const xs=c.options[g.option_group_id]||[];if(xs.length)detail.push(`${g.name}：${xs.map(x=>x.name).join("、")}`)}item={id:state.editingId||cryptoId(),productId:p.product_id,type:p.product_type,categoryKey:categoryKey(p),name:p.name,qty:c.qty,unit:calcRegularUnit(c),detail,variantId:c.variant?.variant_id||null,optionIds:Object.fromEntries(Object.entries(c.options).map(([gid,xs])=>[gid,xs.map(x=>x.option_item_id)]))}}if(state.editingId){const idx=state.cart.findIndex(x=>x.id===state.editingId);if(idx>=0)state.cart[idx]=item}else state.cart.push(item);state.editingId=null;closeProduct();renderCart();toast("購物車已更新")}
function cryptoId(){return `${Date.now()}_${Math.random().toString(36).slice(2,8)}`}
function renderCart(){const count=state.cart.reduce((s,x)=>s+x.qty,0),total=state.cart.reduce((s,x)=>s+x.qty*x.unit,0),blocked=validateCartAvailability();el.cartCount.textContent=count;el.cartTotal.textContent=money(total);el.cartModalTotal.textContent=money(total);el.checkoutTotal.textContent=money(total);el.checkoutBtn.disabled=blocked.length>0||!count;el.checkoutBtn.textContent=blocked.length?"購物車含停止接單商品":"下一步";el.cartBar.classList.toggle("hidden",!count);el.cartItems.innerHTML=state.cart.length?state.cart.map(x=>`<article class="cart-item ${categoryOpen(x.categoryKey||categoryKey(x))?"":"cart-unavailable"}"><div class="cart-item-head"><div><h3>${esc(x.name)}</h3>${x.detail.map(d=>`<p>${esc(d)}</p>`).join("")}${categoryOpen(x.categoryKey||categoryKey(x))?"":`<p class="availability-warning">此分類已停止接單，請移除後再結帳</p>`}</div><strong>${money(x.unit*x.qty)}</strong></div><div class="cart-actions"><div class="cart-secondary-actions"><button class="remove-btn" data-remove="${x.id}">移除</button><button class="edit-btn" data-edit="${x.id}">編輯</button></div><div class="mini-qty"><button data-cartqty="-1" data-id="${x.id}">−</button><strong>${x.qty}</strong><button data-cartqty="1" data-id="${x.id}">＋</button></div></div></article>`).join(""):`<div class="empty-state">購物車還是空的</div>`;el.cartItems.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{state.cart=state.cart.filter(x=>x.id!==b.dataset.remove);renderCart()});el.cartItems.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editCartItem(b.dataset.edit));el.cartItems.querySelectorAll("[data-cartqty]").forEach(b=>b.onclick=()=>{const x=state.cart.find(x=>x.id===b.dataset.id);if(!x)return;x.qty+=Number(b.dataset.cartqty);if(x.qty<=0)state.cart=state.cart.filter(y=>y.id!==x.id);renderCart()});saveCart()}
function editCartItem(id){const item=state.cart.find(x=>x.id===id),p=state.displayProducts.find(x=>x.product_id===item?.productId);if(!item||!p)return toast("找不到商品資料");closeCart();openProduct(p,item)}
function cartTotal(){return state.cart.reduce((s,x)=>s+x.qty*x.unit,0)}
function showModal(node){node.classList.remove("hidden");document.body.style.overflow="hidden"}
function hideModal(node){node.classList.add("hidden");if(!document.querySelector(".modal:not(.hidden)"))document.body.style.overflow=""}
function closeProduct(){hideModal(el.productModal);state.editingId=null}function closeCart(){hideModal(el.cartModal)}function closeCheckout(){hideModal(el.checkoutModal)}function closeResult(){hideModal(el.orderResultModal)}
function showMenu(){el.menuSection.classList.remove("hidden");setTimeout(()=>el.menuSection.scrollIntoView({behavior:"smooth",block:"start"}),40)}
function buildPickupTimes(){const now=new Date(),step=15,minLead=15,start=new Date(now.getTime()+minLead*60000);start.setMinutes(Math.ceil(start.getMinutes()/step)*step,0,0);const opts=[];for(let i=0;i<16;i++){const d=new Date(start.getTime()+i*step*60000);opts.push(`<option value="${d.toISOString()}">${d.toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit",hour12:false})}</option>`)}el.pickupTime.innerHTML=opts.join("")}
async function openCheckout(){if(!state.cart.length)return toast("購物車是空的");await refreshPosStatus(true);const blocked=validateCartAvailability();if(blocked.length)return toast(`${blocked.map(categoryName).join("、")}已停止接單，請先移除相關商品`);closeCart();buildPickupTimes();if(state.profile&&!el.customerName.value)el.customerName.value=state.profile.displayName||"";renderCart();showModal(el.checkoutModal)}
function normalizePhone(v){return String(v||"").replace(/[\s-]/g,"")}
async function submitTestOrder(e){
 e.preventDefault();
 const submitBtn=e.submitter||el.checkoutForm.querySelector('[type="submit"]');
 const name=el.customerName.value.trim(),phone=normalizePhone(el.customerPhone.value);
 if(!name)return toast("請輸入取餐姓名"); if(!/^09\d{8}$/.test(phone))return toast("請輸入正確的手機號碼"); if(!state.cart.length)return toast("購物車是空的");
 await refreshPosStatus(true); const blocked=validateCartAvailability(); if(blocked.length)return toast(`${blocked.map(categoryName).join("、")}已停止接單，訂單無法送出`);
 const clientOrderId=`BH${Date.now()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;
 const payload={api:"online_order_submit",clientOrderId,customerName:name,phone,pickupTime:el.pickupTime.value,note:el.orderNote.value.trim(),lineUserId:state.profile?.userId||"",accessToken:(window.liff&&liff.isLoggedIn()?liff.getAccessToken():""),items:state.cart.map(x=>({productId:x.productId,name:x.name,qty:x.qty,unit:x.unit,detail:x.detail,categoryKey:x.categoryKey||categoryKey(x)}))};
 if(submitBtn){submitBtn.disabled=true;submitBtn.dataset.oldText=submitBtn.textContent;submitBtn.textContent="訂單送出中…"}
 try{
   const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),15000);
   const r=await fetch(cfg.ORDER_SUBMIT_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload),signal:ctrl.signal,redirect:"follow"}); clearTimeout(timer);
   const result=await r.json(); if(!result.ok)throw new Error(result.message||"送單失敗");
   const orderNo=result.orderId||clientOrderId,pickup=new Date(el.pickupTime.value);
   const lines=[`【黑心地瓜球｜線上訂單】`,`訂單編號：${orderNo}`,`取餐姓名：${name}`,`電話：${phone}`,`取餐時間：${pickup.toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit",hour12:false})}`,"",...state.cart.flatMap((x,i)=>[`${i+1}. ${x.name} ×${x.qty}　${money(x.unit*x.qty)}`,...x.detail.map(d=>`   ${d}`)]),"",`合計：${money(cartTotal())}`,`備註：${el.orderNote.value.trim()||"無"}`,"","✅ 訂單已送達店家系統，請留意店家確認。"];
   const localOrder={orderId:orderNo,createdAt:new Date().toISOString(),status:"NEW",customerName:name,phone,pickupTime:el.pickupTime.value,items:state.cart.map(x=>({name:x.name,qty:x.qty,unit:x.unit,detail:Array.isArray(x.detail)?x.detail:[]})),total:cartTotal(),note:el.orderNote.value.trim(),qrToken:""};
   rememberLocalOrder(localOrder);state.myOrders=mergeOrders([],loadLocalOrders());renderMyOrders();
   state.lastOrderText=lines.join("\n"); el.orderResultText.textContent=state.lastOrderText; state.cart=[];renderCart();closeCheckout();showModal(el.orderResultModal);setTimeout(()=>loadMyOrders(true),500);
 }catch(err){console.error(err);toast(err.name==="AbortError"?"送單逾時，請稍後再試；請勿連續重送":"送單失敗："+(err.message||err))}
 finally{if(submitBtn){submitBtn.disabled=false;submitBtn.textContent=submitBtn.dataset.oldText||"送出訂單"}}
}
async function copyOrder(){try{await navigator.clipboard.writeText(state.lastOrderText);toast("訂單內容已複製")}catch{toast("無法自動複製，請長按文字複製")}}
async function loadCatalog(){try{const r=await fetch(cfg.PRODUCTS_URL||"./products.json",{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);state.catalog=await r.json();buildCatalog(state.catalog)}catch(e){console.error(e);el.productList.innerHTML='<div class="empty-state">商品資料載入失敗，請重新整理。</div>';toast("商品資料載入失敗")}}
async function initLine(){el.loginHint.textContent="正在載入 LINE 登入設定…";const id=await resolveLiffId();if(!id){el.loginHint.textContent="尚未設定 LIFF ID；請在 Apps Script 指令碼屬性填入 BLACKHEART_LIFF_ID。";return}if(!window.liff){el.loginHint.textContent="LINE 登入元件載入失敗，請重新整理。";return}try{await liff.init({liffId:id});if(liff.isLoggedIn()){state.profile=await liff.getProfile();el.loginPanel.classList.add("hidden");el.memberPanel.classList.remove("hidden");el.memberName.textContent=state.profile.displayName||"LINE 使用者";if(state.profile.pictureUrl)el.memberPicture.src=state.profile.pictureUrl;else el.memberPicture.classList.add("hidden");if(el.myOrdersBtn)el.myOrdersBtn.classList.remove("hidden");state.myOrders=mergeOrders([],loadLocalOrders());renderMyOrders();await loadMyOrders(true);startMyOrdersPolling()}else{el.loginHint.textContent="請使用 LINE 登入後送出訂單與查看訂單紀錄。"}}catch(e){console.error(e);el.loginHint.textContent="LINE 登入初始化失敗，請確認 LIFF Endpoint URL 為目前 GitHub Pages 網址。"}}

const ORDER_STATUS_META={NEW:['🟡','等待店家接單'],ACCEPTED:['🟢','店家已接單'],READY:['✅','可以取餐'],CHECKOUT:['💰','櫃台結帳中'],PAID:['✔','已付款完成'],REJECTED:['🔴','店家未接單'],CANCELLED:['⚫','已取消'],RELEASED:['✅','可以取餐']};
function orderStatusMeta(s){return ORDER_STATUS_META[String(s||'NEW').toUpperCase()]||['•',String(s||'未知狀態')]}
function orderActive(s){return ['NEW','ACCEPTED','READY','CHECKOUT','RELEASED'].includes(String(s||'').toUpperCase())}
function canCancelAdjusted(o){return String(o.status||'').toUpperCase()==='ACCEPTED'&&o.pickupAdjusted&&o.cancelUntil&&Date.now()<new Date(o.cancelUntil).getTime()}
function cancelSeconds(o){return Math.max(0,Math.ceil((new Date(o.cancelUntil).getTime()-Date.now())/1000))}
async function cancelAdjustedOrder(id){const o=state.myOrders.find(x=>String(x.orderId)===String(id));if(!o||!canCancelAdjusted(o))return toast('取消時間已結束');if(!confirm('確定取消這張訂單？'))return;try{const token=liff.getAccessToken();const r=await fetch(String(cfg.ORDER_SUBMIT_URL||''),{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({api:'online_order_cancel',accessToken:token,orderId:id})});const d=await r.json();if(!d.ok)throw new Error(d.message||'取消失敗');toast('訂單已取消');await loadMyOrders(true);closeOrderDetail()}catch(e){toast(e.message||'取消失敗')}}
function shortOrderId(id){const s=String(id||'');return '#'+(s.includes('-')?s.split('-').pop():s.slice(-6))}
function orderTimeText(v){const d=new Date(v);return isNaN(d)?String(v||''):d.toLocaleString('zh-TW',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})}
function orderPickupText(v){const d=new Date(v);return isNaN(d)?String(v||''):d.toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',hour12:false})}
async function loadMyOrders(silent=false){
 if(!state.profile||!window.liff||!liff.isLoggedIn()||state.myOrdersBusy)return;
 state.myOrdersBusy=true;
 const local=loadLocalOrders();
 if(!state.myOrders.length&&local.length){state.myOrders=mergeOrders([],local);renderMyOrders()}
 try{
   const token=liff.getAccessToken();if(!token)throw new Error('LINE 登入已失效');
   const res=await fetch(String(cfg.ORDER_SUBMIT_URL||""),{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({api:'my_orders',accessToken:token,days:3})});
   const d=await res.json();if(!d.ok)throw new Error(d.message||'讀取訂單失敗');
   state.myOrders=mergeOrders(Array.isArray(d.orders)?d.orders:[],local);saveLocalOrders(state.myOrders);renderMyOrders();
 }catch(e){
   console.error('我的訂單讀取失敗',e);state.myOrders=mergeOrders([],local);renderMyOrders(e.message||'目前無法連線讀取訂單');if(!silent)toast(e.message||'目前無法讀取訂單紀錄');
 }finally{state.myOrdersBusy=false}
}
function startMyOrdersPolling(){clearInterval(state.myOrdersTimer);state.myOrdersTimer=setInterval(()=>{if(document.visibilityState==='visible')loadMyOrders(true)},15000)}
function renderMyOrders(errorMessage=""){
 const active=state.myOrders.filter(o=>orderActive(o.status));if(el.myOrdersBadge)el.myOrdersBadge.textContent=active.length?' '+active.length:'';
 if(el.currentOrderPanel){if(!active.length){el.currentOrderPanel.classList.add('hidden');el.currentOrderPanel.innerHTML=''}else{const o=active[0],m=orderStatusMeta(o.status),cancel=canCancelAdjusted(o);el.currentOrderPanel.classList.remove('hidden');el.currentOrderPanel.innerHTML=`<div><span class="current-order-kicker">📦 目前訂單 ${esc(shortOrderId(o.orderId))}</span><strong>${m[0]} ${esc(m[1])}</strong><small>確認取餐 ${esc(orderPickupText(o.pickupTime))}${cancel?`｜可取消 ${cancelSeconds(o)} 秒`:''}</small></div><button type="button" data-current-order>查看訂單</button>`;el.currentOrderPanel.querySelector('[data-current-order]').onclick=()=>openOrderDetail(o.orderId)}}
 if(!el.myOrdersList)return;el.myOrdersList.innerHTML=state.myOrders.length?state.myOrders.map(o=>{const m=orderStatusMeta(o.status);return `<button class="my-order-card" type="button" data-order-id="${esc(o.orderId)}"><span><b>${esc(shortOrderId(o.orderId))}</b><small>${esc(orderTimeText(o.createdAt))}｜取餐 ${esc(orderPickupText(o.pickupTime))}</small></span><strong>${m[0]} ${esc(m[1])}</strong><em>${money(o.total)}</em></button>`}).join(''):`<div class="empty-state">${errorMessage?`雲端訂單讀取失敗：${esc(errorMessage)}<br>仍可查看此手機剛送出的訂單`:'最近 3 天沒有訂單'}</div>`;el.myOrdersList.querySelectorAll('[data-order-id]').forEach(b=>b.onclick=()=>openOrderDetail(b.dataset.orderId));
}
function openMyOrders(){renderMyOrders();showModal(el.myOrdersModal);loadMyOrders(true)}
function closeMyOrders(){hideModal(el.myOrdersModal)}
function closeOrderDetail(){hideModal(el.orderDetailModal)}
function openOrderDetail(id){const o=state.myOrders.find(x=>String(x.orderId)===String(id));if(!o)return;const m=orderStatusMeta(o.status),items=Array.isArray(o.items)?o.items:[],cancel=canCancelAdjusted(o);el.orderDetailContent.innerHTML=`<p class="section-label">ORDER DETAIL</p><h2>${esc(shortOrderId(o.orderId))}</h2><div class="order-status-large">${m[0]} ${esc(m[1])}</div><div class="order-detail-meta"><span>下單：${esc(orderTimeText(o.createdAt))}</span><span>${o.pickupAdjusted?'店家確認':'取餐'}：${esc(orderPickupText(o.pickupTime))}</span></div>${o.pickupAdjusted?`<p class="order-note">原希望時間：${esc(orderPickupText(o.requestedPickupTime||o.pickupTime))}</p>`:''}<div class="order-detail-items">${items.map(x=>`<div><span><b>${esc(x.name||'商品')} ×${Number(x.qty||1)}</b><small>${(Array.isArray(x.detail)?x.detail:[]).map(esc).join('／')}</small></span><strong>${money(Number(x.unit||0)*Number(x.qty||1))}</strong></div>`).join('')}</div><div class="cart-summary"><span>合計</span><strong>${money(o.total)}</strong></div>${o.note?`<p class="order-note">備註：${esc(o.note)}</p>`:''}${cancel?`<button id="cancelAdjustedOrderBtn" class="primary-btn" type="button">時間無法配合，取消訂單（${cancelSeconds(o)} 秒）</button>`:''}<div id="orderQrBox" class="order-qr-box ${['ACCEPTED','READY','CHECKOUT','RELEASED'].includes(String(o.status).toUpperCase())?'':'hidden'}"><canvas id="orderQrCanvas"></canvas><b>到店可出示此 QR Code</b><small>也可報訂單短碼 ${esc(shortOrderId(o.orderId))}</small></div>`;showModal(el.orderDetailModal);const cb=document.getElementById('cancelAdjustedOrderBtn');if(cb)cb.onclick=()=>cancelAdjustedOrder(o.orderId);setTimeout(()=>{const c=document.getElementById('orderQrCanvas');if(c&&window.QRCode&&o.qrToken)QRCode.toCanvas(c,`BHORDER|${o.orderId}|${o.qrToken}`,{width:210,margin:1}).catch(console.error)},30)}

el.lineLoginBtn.onclick=async()=>{const id=await resolveLiffId();if(!id)return toast("尚未設定 LIFF ID，請先完成 Apps Script 設定");if(!window.liff)return toast("LINE 登入元件尚未載入");liff.isLoggedIn()?showMenu():liff.login({redirectUri:location.origin+location.pathname})};
el.previewBtn.onclick=()=>{state.preview=true;showMenu()};el.startOrderBtn.onclick=showMenu;
document.querySelectorAll("[data-close-modal]").forEach(x=>x.onclick=closeProduct);document.querySelectorAll("[data-close-cart]").forEach(x=>x.onclick=closeCart);document.querySelectorAll("[data-close-checkout]").forEach(x=>x.onclick=closeCheckout);document.querySelectorAll("[data-close-result]").forEach(x=>x.onclick=closeResult);
el.clearCartBtn.onclick=()=>{if(!state.cart.length)return toast("購物車已經是空的");if(confirm("確定要清空購物車內全部商品嗎？")){state.cart=[];renderCart();toast("購物車已清空")}};el.cartBar.onclick=()=>{renderCart();showModal(el.cartModal)};el.checkoutBtn.onclick=openCheckout;el.checkoutForm.onsubmit=submitTestOrder;el.copyOrderBtn.onclick=copyOrder;if(el.myOrdersBtn)el.myOrdersBtn.onclick=openMyOrders;document.querySelectorAll("[data-close-my-orders]").forEach(x=>x.onclick=closeMyOrders);document.querySelectorAll("[data-close-order-detail]").forEach(x=>x.onclick=closeOrderDetail);el.continueOrderBtn.onclick=()=>{closeResult();showMenu()};
syncAccepting();renderTestControls();
for(const [key,node] of [["balls",el.testBalls],["drinks",el.testDrinks],["meals",el.testMeals]])if(node)node.onchange=()=>{state.accepting[key]=node.checked;saveAccepting();renderTestControls();renderProducts();renderCart();toast(`${categoryName(key)}已${node.checked?"開放":"停止"}接單`)};
setStore();renderCart();loadCatalog();initLine();startPosStatusPolling();
})();
