(()=>{"use strict";
const cfg=window.BLACK_HEART_CONFIG||{};
const $=id=>document.getElementById(id);
const el={storeStatus:$("storeStatus"),statusDot:$("statusDot"),waitMinutes:$("waitMinutes"),storeNotice:$("storeNotice"),loginPanel:$("loginPanel"),memberPanel:$("memberPanel"),memberName:$("memberName"),memberPicture:$("memberPicture"),lineLoginBtn:$("lineLoginBtn"),previewBtn:$("previewBtn"),startOrderBtn:$("startOrderBtn"),loginHint:$("loginHint"),menuSection:$("menuSection"),categoryTabs:$("categoryTabs"),productList:$("productList"),catalogMeta:$("catalogMeta"),productModal:$("productModal"),modalContent:$("modalContent"),cartBar:$("cartBar"),cartCount:$("cartCount"),cartTotal:$("cartTotal"),cartModal:$("cartModal"),cartItems:$("cartItems"),cartModalTotal:$("cartModalTotal"),checkoutBtn:$("checkoutBtn"),toast:$("toast")};
const state={catalog:null,categories:[],displayProducts:[],activeCategory:"balls",cart:[],profile:null,preview:false,current:null};
const money=n=>`NT$${Number(n||0).toLocaleString("zh-TW")}`;
function toast(m){el.toast.textContent=m;el.toast.classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.add("hidden"),2600)}
function setStore(){const s=cfg.STORE||{};el.storeStatus.textContent=s.statusText||(s.isOpen?"今日營業中":"今日暫停接單");el.waitMinutes.textContent=s.isOpen?(s.waitText||"約 10–12 分鐘"):"暫停接單";el.storeNotice.textContent=s.notice||"";el.statusDot.classList.toggle("closed",!s.isOpen)}
function isHidden(p){const words=cfg.HIDDEN_PRODUCT_KEYWORDS||[];return !p.enabled||words.some(w=>String(p.name||"").includes(w))}
function buildCatalog(raw){const products=(raw.products||[]).filter(p=>!isHidden(p));const balls=products.filter(p=>p.product_type==="ball").sort((a,b)=>a.sort_order-b.sort_order);const nonBalls=products.filter(p=>p.product_type!=="ball");const ballCard=balls.length?{product_id:"online_ball_bundle",category_id:"balls",name:cfg.BALL_PRODUCT_NAME||"黑心地瓜球",product_type:"ball_bundle",base_price:Math.min(...balls.map(x=>Number(x.base_price||0))),flavors:balls,enabled:true,sort_order:0}:null;state.displayProducts=[...(ballCard?[ballCard]:[]),...nonBalls].filter(p=>p.enabled!==false);const used=new Set(state.displayProducts.map(p=>p.category_id));state.categories=(raw.categories||[]).filter(c=>c.enabled&&used.has(c.category_id)&&c.category_id!=="hot"&&c.category_id!=="drinks").sort((a,b)=>a.sort_order-b.sort_order);if(!state.categories.some(c=>c.category_id===state.activeCategory))state.activeCategory=state.categories[0]?.category_id||"";el.catalogMeta.textContent=`${state.displayProducts.length} 項`;renderTabs();renderProducts()}
function renderTabs(){el.categoryTabs.innerHTML=state.categories.map(c=>`<button class="category-tab ${c.category_id===state.activeCategory?"active":""}" data-cat="${esc(c.category_id)}">${esc(c.name)}</button>`).join("");el.categoryTabs.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{state.activeCategory=b.dataset.cat;renderTabs();renderProducts()})}
function priceText(p){if(p.product_type==="ball_bundle")return `${money(p.base_price)} 起`;const vars=(p.variants||[]).filter(v=>v.enabled);if(vars.length){const xs=vars.map(v=>Number(v.price));return Math.min(...xs)===Math.max(...xs)?money(xs[0]):`${money(Math.min(...xs))} 起`}return money(p.base_price)}
function iconFor(p){return p.product_type==="drink"?"🥤":p.product_type==="meal"?"🍱":"🍠"}
function renderProducts(){const list=state.displayProducts.filter(p=>p.category_id===state.activeCategory).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));el.productList.innerHTML=list.length?list.map(p=>`<button class="product-card" data-product="${esc(p.product_id)}"><div class="product-placeholder">${iconFor(p)}</div><div class="product-info"><h3>${esc(p.name)}</h3><p>${p.product_type==="ball_bundle"?"最多選 2 種口味・價格取最高價":productHint(p)}</p></div><strong class="product-price">${priceText(p)}</strong></button>`).join(""):`<div class="empty-state">此分類目前沒有商品</div>`;el.productList.querySelectorAll("[data-product]").forEach(b=>b.onclick=()=>openProduct(state.displayProducts.find(p=>p.product_id===b.dataset.product)))}
function productHint(p){const bits=[];if((p.variants||[]).filter(v=>v.enabled).length)bits.push("可選尺寸");for(const g of p.option_groups||[])if(g.name&&!bits.includes(g.name))bits.push(g.name);return bits.length?bits.join("・"):"點選查看"}
function openProduct(p){if(!p)return;state.current={p,qty:1,flavors:[],variant:null,options:{}};if(p.product_type==="ball_bundle")renderBallModal();else renderRegularModal();el.productModal.classList.remove("hidden");document.body.style.overflow="hidden"}
function renderBallModal(){const c=state.current,p=c.p;const highest=c.flavors.length?Math.max(...c.flavors.map(x=>Number(x.base_price))):Number(p.base_price);el.modalContent.innerHTML=`<div class="modal-title"><p class="section-label">地瓜球</p><h2 id="modalTitle">${esc(p.name)}</h2><p>一份最多選 2 種口味，價格以所選口味中的最高價計算。</p></div><section class="choice-section"><h3>選擇口味</h3><p class="choice-help">至少選 1 種，最多 2 種</p><div class="choice-grid">${p.flavors.map(f=>`<button class="choice ${c.flavors.some(x=>x.product_id===f.product_id)?"selected":""}" data-flavor="${esc(f.product_id)}"><span>${esc(f.name)}</span><small>${money(f.base_price)}</small></button>`).join("")}</div></section>${qtyHtml(c.qty)}<div class="add-row"><button id="addCurrentBtn" class="primary-btn" ${c.flavors.length?"":"disabled"}><span>加入購物車</span><strong>${money(highest*c.qty)}</strong></button></div>`;el.modalContent.querySelectorAll("[data-flavor]").forEach(b=>b.onclick=()=>{const f=p.flavors.find(x=>x.product_id===b.dataset.flavor),i=c.flavors.findIndex(x=>x.product_id===f.product_id);if(i>=0)c.flavors.splice(i,1);else if(c.flavors.length>=2)return toast("最多選擇 2 種口味");else c.flavors.push(f);renderBallModal()});bindQty();$("addCurrentBtn")?.addEventListener("click",addCurrent)}
function renderRegularModal(){const c=state.current,p=c.p;const vars=(p.variants||[]).filter(v=>v.enabled).sort((a,b)=>a.sort_order-b.sort_order);if(vars.length&&!c.variant)c.variant=vars[0];for(const g of p.option_groups||[]){const items=(g.items||[]).filter(x=>x.enabled).sort((a,b)=>a.sort_order-b.sort_order);if(g.required&&!c.options[g.option_group_id]&&items.length)c.options[g.option_group_id]=[items[0]]}const base=c.variant?Number(c.variant.price):Number(p.base_price);const delta=Object.values(c.options).flat().reduce((s,x)=>s+Number(x.price_delta||0),0);const unit=base+delta;const groups=(p.option_groups||[]).map(g=>groupHtml(g,c.options[g.option_group_id]||[])).join("");el.modalContent.innerHTML=`<div class="modal-title"><p class="section-label">${esc(p.category_name||"商品")}</p><h2 id="modalTitle">${esc(p.name)}</h2><p>${productHint(p)}</p></div>${vars.length?`<section class="choice-section"><h3>尺寸</h3><div class="choice-grid">${vars.map(v=>`<button class="choice ${c.variant?.variant_id===v.variant_id?"selected":""}" data-variant="${esc(v.variant_id)}"><span>${esc(v.name)}</span><small>${money(v.price)}</small></button>`).join("")}</div></section>`:""}${groups}${qtyHtml(c.qty)}<div class="add-row"><button id="addCurrentBtn" class="primary-btn"><span>加入購物車</span><strong>${money(unit*c.qty)}</strong></button></div>`;el.modalContent.querySelectorAll("[data-variant]").forEach(b=>b.onclick=()=>{c.variant=vars.find(v=>v.variant_id===b.dataset.variant);renderRegularModal()});el.modalContent.querySelectorAll("[data-option]").forEach(b=>b.onclick=()=>toggleOption(b.dataset.group,b.dataset.option));bindQty();$("addCurrentBtn").onclick=addCurrent}
function groupHtml(g,selected){const items=(g.items||[]).filter(x=>x.enabled).sort((a,b)=>a.sort_order-b.sort_order);return `<section class="choice-section"><h3>${esc(g.name)}${g.required?" *":""}</h3><p class="choice-help">${g.max_select===1?"請選擇 1 項":`最多選 ${g.max_select} 項`}</p><div class="choice-grid">${items.map(x=>`<button class="choice ${selected.some(s=>s.option_item_id===x.option_item_id)?"selected":""}" data-group="${esc(g.option_group_id)}" data-option="${esc(x.option_item_id)}"><span>${esc(x.name)}</span><small>${Number(x.price_delta)?`+${money(x.price_delta)}`:""}</small></button>`).join("")}</div></section>`}
function toggleOption(gid,oid){const c=state.current,g=(c.p.option_groups||[]).find(x=>x.option_group_id===gid),item=(g.items||[]).find(x=>x.option_item_id===oid),arr=c.options[gid]||[],i=arr.findIndex(x=>x.option_item_id===oid);if(g.max_select===1)c.options[gid]=i>=0&&!g.required?[]:[item];else if(i>=0)arr.splice(i,1);else if(arr.length<(g.max_select||99))arr.push(item);else return toast(`最多選擇 ${g.max_select} 項`);renderRegularModal()}
function qtyHtml(q){return `<div class="qty-row"><strong>數量</strong><div class="qty-control"><button data-qty="-1">−</button><strong>${q}</strong><button data-qty="1">＋</button></div></div>`}
function bindQty(){el.modalContent.querySelectorAll("[data-qty]").forEach(b=>b.onclick=()=>{state.current.qty=Math.max(1,Math.min(99,state.current.qty+Number(b.dataset.qty)));state.current.p.product_type==="ball_bundle"?renderBallModal():renderRegularModal()})}
function addCurrent(){const c=state.current,p=c.p;let unit,detail=[];if(p.product_type==="ball_bundle"){if(!c.flavors.length)return;unit=Math.max(...c.flavors.map(x=>Number(x.base_price)));detail.push(`口味：${c.flavors.map(x=>x.name).join("＋")}`)}else{unit=c.variant?Number(c.variant.price):Number(p.base_price);if(c.variant)detail.push(`尺寸：${c.variant.name}`);for(const g of p.option_groups||[]){const xs=c.options[g.option_group_id]||[];if(xs.length){detail.push(`${g.name}：${xs.map(x=>x.name).join("、")}`);unit+=xs.reduce((s,x)=>s+Number(x.price_delta||0),0)}}}state.cart.push({id:`${Date.now()}_${Math.random()}`,name:p.name,qty:c.qty,unit,detail});closeModal();renderCart();toast("已加入購物車")}
function renderCart(){const count=state.cart.reduce((s,x)=>s+x.qty,0),total=state.cart.reduce((s,x)=>s+x.qty*x.unit,0);el.cartCount.textContent=count;el.cartTotal.textContent=money(total);el.cartModalTotal.textContent=money(total);el.cartBar.classList.toggle("hidden",!count);el.cartItems.innerHTML=state.cart.length?state.cart.map(x=>`<article class="cart-item" data-cart="${x.id}"><div class="cart-item-head"><div><h3>${esc(x.name)}</h3>${x.detail.map(d=>`<p>${esc(d)}</p>`).join("")}</div><strong>${money(x.unit*x.qty)}</strong></div><div class="cart-actions"><button class="remove-btn" data-remove="${x.id}">移除</button><div class="mini-qty"><button data-cartqty="-1" data-id="${x.id}">−</button><strong>${x.qty}</strong><button data-cartqty="1" data-id="${x.id}">＋</button></div></div></article>`).join(""):`<div class="empty-state">購物車還是空的</div>`;el.cartItems.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{state.cart=state.cart.filter(x=>x.id!==b.dataset.remove);renderCart()});el.cartItems.querySelectorAll("[data-cartqty]").forEach(b=>b.onclick=()=>{const x=state.cart.find(x=>x.id===b.dataset.id);if(!x)return;x.qty+=Number(b.dataset.cartqty);if(x.qty<=0)state.cart=state.cart.filter(y=>y.id!==x.id);renderCart()})}
function closeModal(){el.productModal.classList.add("hidden");document.body.style.overflow=""}function closeCart(){el.cartModal.classList.add("hidden");document.body.style.overflow=""}
function showMenu(){el.menuSection.classList.remove("hidden");setTimeout(()=>el.menuSection.scrollIntoView({behavior:"smooth",block:"start"}),40)}
async function loadCatalog(){try{const r=await fetch(cfg.PRODUCTS_URL||"./products.json",{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);state.catalog=await r.json();buildCatalog(state.catalog)}catch(e){console.error(e);el.productList.innerHTML='<div class="empty-state">商品資料載入失敗，請重新整理。</div>';toast("商品資料載入失敗")}}
async function initLine(){const id=String(cfg.LIFF_ID||"").trim();if(!id){el.loginHint.textContent="尚未填入 LIFF ID；目前可先預覽完整點餐流程。";return}if(!window.liff){el.loginHint.textContent="LINE 登入元件載入失敗，請重新整理。";return}try{await liff.init({liffId:id});if(liff.isLoggedIn()){state.profile=await liff.getProfile();el.loginPanel.classList.add("hidden");el.memberPanel.classList.remove("hidden");el.memberName.textContent=state.profile.displayName||"LINE 使用者";if(state.profile.pictureUrl)el.memberPicture.src=state.profile.pictureUrl;else el.memberPicture.classList.add("hidden")}}catch(e){console.error(e);el.loginHint.textContent="LINE 登入初始化失敗，請檢查 LIFF ID 與 Endpoint URL。"}}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
el.lineLoginBtn.onclick=()=>{const id=String(cfg.LIFF_ID||"").trim();if(!id)return toast("請先完成 LIFF 設定並填入 LIFF ID");if(!window.liff)return toast("LINE 登入元件尚未載入");liff.isLoggedIn()?showMenu():liff.login({redirectUri:location.href})};el.previewBtn.onclick=()=>{state.preview=true;showMenu()};el.startOrderBtn.onclick=showMenu;document.querySelectorAll("[data-close-modal]").forEach(x=>x.onclick=closeModal);document.querySelectorAll("[data-close-cart]").forEach(x=>x.onclick=closeCart);el.cartBar.onclick=()=>{renderCart();el.cartModal.classList.remove("hidden");document.body.style.overflow="hidden"};el.checkoutBtn.onclick=()=>{if(!state.cart.length)return toast("購物車是空的");if(!state.profile&&!state.preview)return toast("請先使用 LINE 登入");toast("下一階段會接上訂單送出與 POS 接單")};
setStore();loadCatalog();initLine();})();